// Run `node game/build-meatly.cjs` after editing the PDE files or sprite.
// Bundle the sketch and image so opening the HTML via file:// needs no XHR.
const fs = require('node:fs');
const path = require('node:path');
const read = file => fs.readFileSync(path.join(__dirname, file), 'utf8');
const sprite = 'data:image/png;base64,' + fs.readFileSync(path.join(__dirname, 'images/meatly_idle.png')).toString('base64');
const source = read('levels.pde') + '\n' + read('anything.pde').replace('"images/meatly_idle.png"', JSON.stringify(sprite));
fs.writeFileSync(path.join(__dirname, 'meatly-sketch.js'),
  '// Generated by build-meatly.cjs; edit the original PDE files instead.\n' +
  'new Processing(document.getElementById("meatly-game"), ' + JSON.stringify(source) + ');\n');
